version: '3'

services:
  mongo_db:
    container_name: database_team
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 8000:4000
    environment:
      MONGO_URI: mongodb+srv://ajor123:NandePan@ajor123.qvctqss.mongodb.net/
      PORT: 4000
      JWT_SECRET: "slejffofmcikeoAiwe@234SAa"
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}